school/library/urls.py
from django.urls import path, include
from .views import HomeView, search, student

app_name = 'library'

urlpatterns = [
    path('', HomeView, name = 'home'),
    path('search/',search, name = 'search'),
    path('student/<int:sid>', student, name = 'student'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace = 'library')),
]

school/library/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length = 100)
    author_name = models.CharField(max_length = 100)
    date_of_publication = models.DateTimeField(blank = True, null = True)
    pages = models.IntegerField(default = 0)


    def __str__(self):
        return self.title
    
class School(models.Model):
    school_name = models.CharField(max_length = 100)
    email = models.EmailField(max_length = 100)
    principal = models.CharField(max_length = 100)
    phone_no = models.CharField(max_length = 100)
    address = models.CharField(max_length = 100)

    def __str__(self):
        return self.school_name

class Student(models.Model):
    sid = models.IntegerField()
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    email  = models.EmailField(max_length = 100)
    gender = models.CharField(max_length = 100)
    pages_read = models.IntegerField(default = 0)

    def __str__(self):
        
        return self.first_name


class Reading(models.Model):
    student = models.ForeignKey(Student, on_delete = models.CASCADE, null=True, blank=True)
    book = models.ForeignKey(Book, on_delete = models.CASCADE, null=True, blank=True)
    school = models.ForeignKey(School, on_delete = models.CASCADE, null = True, blank = True)
    def __str__(self):
        return self.student.first_name
    

school/library/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q 
from django.views.generic import ListView
from .filters import StudentFilter

from .populate import do
from .models import *
import pandas as pd

populate = False


def HomeView(request):
        
    if populate:
        do()
    return render(request, 'home.html')


def search(request):
    student_list = Student.objects.all()
    student_filter = StudentFilter(request.GET, queryset = student_list)
    final = {'filter':student_filter}
    try:
        num = student_filter.qs[0].sid
        obj = Reading.objects.get(student= num)
        # When there are students who read more than one book.
        # print(Reading.objects.filter(student = num)) 
        final['stud'] = student_filter.qs[0]
        final['boo'] = obj  
        final['pg'] = Book.objects.get(title = obj.book)

    except:
        pass

    return render(request, 'results.html', final)


def student(request, sid):
    dic = {}
    obj = Student.objects.get(sid = sid) 
    dic['obj'] = obj
    try:
        obj1 = Reading.objects.get(student = sid)
        dic['school'] = obj1.school
        dic['book'] = obj1.book
        dic['pages'] = Book.objects.get(title = obj1.book)
        print(obj1.book)
    except:
        pass
  
    return render(request, 'student.html', dic) 

school/library/templates/home.html
<h1>HELLO :)</h1>
<h1><a href="{% url 'library:search' %}">Search</a></h1>

school/library/templates/results.html
<h1>Search Results</h1>

<form method="get">
  {{ filter.form.as_p }}
  <button type="submit">Search</button>
</form>


  <!-- {% for user in filter.qs %}
      <li>Name = {{ user.first_name }} - {{ user.last_name }}</li>
  {% endfor %} -->
 
<li>Name - {{stud.first_name}} {{stud.last_name}}</li>
<li>Gender - {{stud.gender}}</li>
<li>Email - {{stud.email}}</li>
<li>Books - {{boo.book}}</li>
<li>School - {{boo.school}}</li>
<li>School No - {{boo.school.phone_no}}</li>

<li>Pages - {{pg.pages}}</li>

school/library/templates/student.html
<h1>Student Info</h1>


<h2>Name - {{obj.first_name}} {{obj.last_name}}</h2>
<h2>Mail - {{obj.email}}</h2>
<h2>Gender - {{obj.gender}}</h2>
<h2>School - {{school.school_name}}  </h2>
<h2>School No- {{school.phone_no}}</h2>
<h2>Book - {{book}}</h2>
<h2>Pages - {{pages.pages}}</h2>